tests/core/CMakeLists.txt
tests/core/basic/test.cmake
tests/core/core-helpers.cmake
tests/core/crash/test.cmake
tests/core/dirs/test.cmake
tests/core/getdents/test.cmake
tests/core/mt/test.cmake
tests/core/openp/test.cmake
tests/core/rw/test.cmake
tests/core/stat/test.cmake
tests/core/symlinks/test.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/4)

Introduce TEST_EXECUTABLE arg in core tests

---

tests/core/crash/crash.cpp

Ref: marcinslusarz/pmemfile#12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/14)

tests: fix build with clang

---

src/libpmemfile-core/data.c

Remove the argument named file, and use vinode instead.
This, file_allocate_range can be used on inodes without an open
pmemfile file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/9)

refactor file_allocate_range routine - file arg

---

src/libpmemfile-core/data.c
src/libpmemfile-core/layout.h
tests/core/rw/rw.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/6)

core: layout change - introduce prev field in pmemfile_block

---

src/libpmemfile-core/dir.c
src/libpmemfile-core/dir.h
src/libpmemfile-core/file.c
src/libpmemfile-core/inode.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/18)

core: share symlink resolving code

---

src/libpmemfile-core/file.c
tests/core/symlinks/symlinks.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/19)

core: fix interaction between symlinks and open flags

---

src/libpmemfile-core/data.c
src/libpmemfile-core/inode.h
tests/core/rw/rw.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/28)

Snapshot vinode

---

tests/core/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/35)

core: enable CMAKE_POSITION_INDEPENDENT_CODE

---

tests/core/CMakeLists.txt
tests/core/rw/test.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/36)

tests: enable some RW tests with pmemcheck

---

CMakeLists.txt
tests/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/37)

cmake: add help messages for some variables

---

debian/debug/rules
debian/rules
pmemfile-debug.spec
pmemfile.spec
utils/build-deb.sh
utils/docker/run-build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/39)

travis: use more cores

---

src/libpmemfile-core/CMakeLists.txt
src/libpmemfile-core/block_array.c
src/libpmemfile-core/data.c
src/libpmemfile-core/inode.h

Introduce routines allocate_new_block_metadata and
unlink_and_release_block_metadata.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/33)

core: refactor block_array handling

---

src/libpmemfile-core/dir.c
src/libpmemfile-core/dir.h
src/libpmemfile-core/file.c
src/libpmemfile-core/file.h
src/libpmemfile-core/inode.c
src/libpmemfile-core/inode.h
src/libpmemfile-core/pool.c
src/libpmemfile-core/pool.h
tests/core/permissions/permissions.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/42)

posix: more permission checks

---

CMakeLists.txt
README.md
tests/core/CMakeLists.txt

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/45)

cmake: s/SANITIZERS_ENABLED/SANITIZERS/g and document SANITIZERS

---

src/libpmemfile-core/dir.c
src/libpmemfile-core/file.c
src/libpmemfile-core/pool.c
src/libpmemfile-core/pool.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/46)

posix: add wrappers around get_perms & can_access

---

src/libpmemfile-core/dir.c
src/libpmemfile-core/file.c
src/libpmemfile-core/inode.c
src/libpmemfile-core/inode.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/51)

posix: add vinode_cleanup

---

src/libpmemfile-core/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/49)

cmake: add dependency between library and linker script

---

src/libpmemfile-core/file.c
src/libpmemfile-core/inode.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/48)

posix: fix potential null-ptr dereference in fstat and chmod

---

src/libpmemfile-core/block_array.c
src/libpmemfile-core/data.c
src/libpmemfile-core/data.h
src/libpmemfile-core/file.c
src/libpmemfile-core/inode.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/41)

Vinode truncate changes

---

src/libpmemfile-core/dir.c
src/libpmemfile-core/dir.h
src/libpmemfile-core/file.c
src/libpmemfile-core/inode.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/57)

posix: share full path resolving code

---

include/libpmemfile-posix.h
src/libpmemfile-core/file.c
src/libpmemfile-core/libpmemfile-posix.map
src/libpmemfile-core/pool.c
src/libpmemfile-core/pool.h
tests/core/permissions/permissions.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/50)

posix: add pmemfile_setcap, pmemfile_clrcap and use it in chmod

---

include/libpmemfile-posix-stubs.h
include/libpmemfile-posix.h
src/libpmemfile-core/file.c
src/libpmemfile-core/stubs.c
tests/core/rw/rw.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/55)

posix: implement pmemfile_[f]truncate

---

src/libpmemfile-core/os_util_linux.c
src/libpmemfile/preload.c
tests/core/dirs/dirs.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/59)

Coverity fixes

---

include/libpmemfile-posix-stubs.h
include/libpmemfile-posix.h
src/libpmemfile-core/file.c
src/libpmemfile-core/pool.c
src/libpmemfile-core/pool.h
src/libpmemfile-core/stubs.c
tests/core/permissions/permissions.cpp

Built on top of PR #50
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/56)

posix: implement chown, fchown, lchown

---

src/libpmemfile/path_resolve.c
tests/preload/basic/basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/62)

Preload path resolve fix

---

src/libpmemfile/preload.c
tests/preload/basic/basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/61)

Truncate preload fix

---

tests/posix/basic/basic.cpp
tests/posix/getdents/getdents.cpp
tests/posix/permissions/permissions.cpp
tests/posix/pmemfile_test.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/63)

tests: fix empty dir check

---

tests/posix/dirs/dirs.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/67)

tests: add tests for mkdirat and unlinkat

---

src/libpmemfile-posix/data.c

Not tested yet, the fallocate tests do exercise this code path -- coming soon
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/68)

posix: allocate_interval fix

---

src/libpmemfile-posix/file.c
tests/posix/dirs/dirs.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/69)

tests: add test for openat

---

src/libpmemfile-posix/data.c

The fourth case, that was forgotten so far.
Tests which exercise this code path are coming later, with fallocate i.e.:
https://github.com/GBuella/pmemfile/blob/fallocate/tests/posix/rw/rw.cpp#L670
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/71)

posix: vinode_remove_interval fix

---

src/libpmemfile-posix/file.c
tests/posix/dirs/dirs.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/72)

posix: implement AT_EMPTY_PATH for linkat

---

src/libpmemfile-posix/file.c
tests/posix/dirs/dirs.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/75)

posix: implement AT_EMPTY_PATH for fchownat

---

src/libpmemfile/preload.c
tests/preload/basic/basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/80)

Libpmemfile fallocate

---

src/libpmemfile-posix/data.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/82)

posix: fallocate - file size bugfix

---

include/libpmemfile-posix.h
src/libpmemfile-posix/file.c
src/libpmemfile-posix/libpmemfile-posix.map
tests/posix/rw/rw.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/81)

posix: add pmemfile_posix_fallocate interface

---

src/libpmemfile-posix/layout.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/85)

posix: quiet down clang analyzer warnings related to D_RW/D_RO

---

src/libpmemfile-posix/inode.c

They are not really needed and here add some overhead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/86)

posix: remove use of callbacks in vinode_unref

---

src/libpmemfile/preload.c

The only flag specified in fchmodat manpage is documented as
not implemented and Linux kernel interface does not have it,
so libc doesn't fill this argument and we get garbage as flags.
Just remove it.
Ref: marcinslusarz/pmemfile#89
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/90)

preload: fix fchmodat

---

src/libpmemfile-posix/data.c
tests/posix/rw/rw.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/91)

Lseek data and hole

---

src/libpmemfile-posix/data.c
tests/posix/rw/rw.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/93)

posix: lseek -- minor fixes regarding error codes

---

CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/99)

cmake: Remove some manual flag setting

---

CMakeLists.txt
doc/CMakeLists.txt
src/libpmemfile-posix/CMakeLists.txt
src/libpmemfile/CMakeLists.txt
src/tools/CMakeLists.txt

Ref: pmem/pmemfile#53
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/98)

Add support for RelWithDebInfo build type.

---

src/libpmemfile-posix/data.c
src/libpmemfile-posix/dir.c
src/libpmemfile-posix/file.c
src/libpmemfile-posix/inode.c
src/libpmemfile-posix/pool.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/101)

posix: add pool & file NULL checks

---

CMakeLists.txt
tests/CMakeLists.txt
tests/helpers.cmake
tests/match
utils/check_license/check-headers.sh
utils/check_license/check-license.c
utils/check_whitespace
utils/cstyle

When build directory is not a child of source dir check-license
complains about missing .git directory and fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/100)

check-license: fix out of tree builds

---

src/libpmemfile/preload.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/104)

preload: handle fsync

---

LICENSE
cmake_uninstall.cmake.in

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/106)

Mention origin of cmake_uninstall_license.cmake.in

---

CMakeLists.txt
src/libpmemfile-posix/CMakeLists.txt
src/libpmemfile/CMakeLists.txt

Also, mark libs used by lipmemfile as PRIVATE.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/110)

cmake: use CMAKE_THREAD_LIBS_INIT cmake variable

---

include/libpmemfile-posix-stubs.h
src/libpmemfile-posix/data.c
src/libpmemfile-posix/stubs.c
tests/posix/rw/rw.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/119)

posix: vector reads & writes

---

tests/posix/mt/mt.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/116)

tests: replace pthreads with std::thread

---

src/libpmemfile/path_resolve.c
src/libpmemfile/preload.c
src/libpmemfile/preload.h
tests/preload/basic_commands/basic_commands.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/118)

preload: fix path handling when resolution points to kernel fs

---

tests/posix/mt/mt.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/120)

tests: create at least one thread in "mt" test when ncpus=1

---

src/libpmemfile-posix/data.c
tests/posix/rw/rw.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/121)

posix: optimize (p)writev by calling vinode_allocate_interval once

---

include/libpmemfile-posix-stubs.h
include/libpmemfile-posix.h

I forgot to do that when implementing them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/123)

posix: move vector functions to main header file

---

src/libpmemfile/preload.c
utils/docker/images/install-syscall_intercept.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/127)

travis: update syscall_intercept reference

---

src/libpmemfile-posix/data.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/129)

posix: data.c -- some descriptions about interval allocation

---

src/libpmemfile-posix/file.c

Ref: pmem/pmemfile#78
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/130)

posix: call ftruncate and fallocate without file mutex

---

src/libpmemfile-posix/block_array.c
src/libpmemfile-posix/block_array.h
src/libpmemfile-posix/data.c
src/libpmemfile-posix/inode.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/128)

block_array related refactor - based on review

---

src/libpmemfile/preload.c
src/libpmemfile/sys_util.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/133)

Libpmemfile fixes 0

---

src/libpmemfile/preload.c
src/libpmemfile/preload.h
src/libpmemfile/sys_util.h
tests/preload/CMakeLists.txt
tests/preload/config/config.c
tests/preload/config/config.cmake

Related to previous review comment by @pbalcer :
"I really don't understand the reason for those atomic operations.
This function is not thread safe anyway."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/134)

Libpmemfile fixes 1

---

src/libpmemfile-posix/CMakeLists.txt
src/libpmemfile/preload.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/137)

Gabor review fixes 5

---

src/libpmemfile/preload.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/139)

preload: remove unused "strict symlink" code

---

src/libpmemfile/path_resolve.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/140)

Gabor review fixes 7

---

src/libpmemfile/path_resolve.c
src/libpmemfile/preload.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/145)

Miscellaneous fixes based on code review

---

.travis.yml
README.md
codecov.yml
utils/docker/run-coverage.sh

Codecov.io provides nice interface to information about project's code coverage.
Example report:
https://codecov.io/gh/marcinslusarz/pmemfile/tree/6cfe036a65f6651a57e8d8fb31af247806db315c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/148)

Integrate codecov.io

---

src/libpmemfile-posix/access.c
src/libpmemfile-posix/chmod.c
src/libpmemfile-posix/chown.c
src/libpmemfile-posix/dir.c
src/libpmemfile-posix/link.c
src/libpmemfile-posix/stat.c
tests/posix/permissions/permissions.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/153)

tests: increase code coverage of pmemfile_*access* functions

---

src/libpmemfile/preload.c

... and reorder functions to let it compile.
No other changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/158)

preload: remove forward declarations

---

src/libpmemfile-posix/out.c
src/libpmemfile-posix/out.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/155)

posix: remove dead code from out.c

---

src/libpmemfile-posix/access.c
src/libpmemfile-posix/block_array.c
src/libpmemfile-posix/chdir.c
src/libpmemfile-posix/chmod.c
src/libpmemfile-posix/chown.c
src/libpmemfile-posix/data.c
src/libpmemfile-posix/dir.c
src/libpmemfile-posix/fallocate.c
src/libpmemfile-posix/file.c
src/libpmemfile-posix/inode.c
src/libpmemfile-posix/inode_array.c
src/libpmemfile-posix/link.c
src/libpmemfile-posix/locks.c
src/libpmemfile-posix/mkdir.c
src/libpmemfile-posix/pool.c
src/libpmemfile-posix/read.c
src/libpmemfile-posix/readlink.c
src/libpmemfile-posix/rename.c
src/libpmemfile-posix/rmdir.c
src/libpmemfile-posix/stat.c
src/libpmemfile-posix/symlink.c
src/libpmemfile-posix/truncate.c
src/libpmemfile-posix/unlink.c
src/libpmemfile-posix/utils.h
src/libpmemfile-posix/write.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/156)

posix: check transaction stage in more places

---

src/libpmemfile/preload.c

Refactor only, the functionality remains as it was.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/161)

preload: introduce hook_reentrance_guard_wrapper

---

src/libpmemfile-posix/getdents.c
src/libpmemfile-posix/read.c
src/libpmemfile-posix/rmdir.c
src/libpmemfile-posix/stat.c
src/libpmemfile-posix/write.c
tests/posix/basic/basic.cpp
tests/posix/dirs/dirs.cpp
tests/posix/getdents/getdents.cpp
tests/posix/permissions/permissions.cpp
tests/posix/rw/rw.cpp
tests/posix/stat/stat.cpp
tests/posix/symlinks/symlinks.cpp

Most of the new test cases are trivial.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/154)

Test previously not covered code paths in pmemfile-posix + few bug fixes

---

src/libpmemfile-posix/inode_array.c
src/libpmemfile-posix/inode_array.h
src/libpmemfile-posix/pool.c

... and simplify orphaned_inodes cleanup logic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/160)

posix: move everything related to inode_array to inode_array.c

---

src/libpmemfile-posix/fcntl.c

Ref: #162
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/164)

posix: fix F_SETFD return statement

---

src/libpmemfile-posix/layout.h
src/libpmemfile-posix/pool.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/157)

posix: minor fixes for issues raised in #95, part 3

---

src/libpmemfile-posix/write.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/166)

posix: optimize inode size updates for vector writes

---

src/libpmemfile/path_resolve.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/170)

preload: handle ENAMETOOLONG in resolve_path

---

CMakeLists.txt
debian/libpmemfile-posix-dev.manpages
debian/libpmemfile0.triggers
doc/generated/libpmemfile-posix.3
doc/libpmemfile-posix.3.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/171)

Fixes for issues raised in #95, part 5

---

src/libpmemfile-posix/block_array.c
src/libpmemfile-posix/data.c
src/libpmemfile-posix/dir.c
src/libpmemfile-posix/internal.h
src/libpmemfile-posix/pmemfile-posix.c
src/libpmemfile-posix/utils.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/167)

posix: split FILE_PAGE_SIZE

---

README.md
utils/docker/pull-or-rebuild-image.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/172)

Update/remove references to development branch.

---

src/libpmemfile/preload.c
src/libpmemfile/syscall_early_filter.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/173)

preload: wire up vector reads & writes

---

.travis.yml
README.md
utils/docker/build.sh
utils/docker/pull-or-rebuild-image.sh
utils/docker/run-coverity.sh

Builds on top of #172
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/192)

Integrate Coverity

---

src/libpmemfile-posix/callbacks.c
src/libpmemfile-posix/fallocate.c
src/libpmemfile-posix/internal.h
src/libpmemfile-posix/rename.c
src/libpmemfile-posix/rmdir.c
src/libpmemfile-posix/truncate.c
src/libpmemfile-posix/unlink.c
tests/posix/dirs/dirs.cpp
tests/posix/pmemfile_test.cpp
tests/posix/pmemfile_test.hpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/194)

Coverity fixes / annotations

---

src/libpmemfile-posix/file.c

Failed inode_ref would leave vparent locked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/199)

posix: fix error handling in open

---

src/libpmemfile-posix/chmod.c
src/libpmemfile-posix/chown.c
src/libpmemfile-posix/dir.c
src/libpmemfile-posix/inode.c
src/libpmemfile-posix/link.c
src/libpmemfile-posix/read.c
src/libpmemfile-posix/rename.c
src/libpmemfile-posix/rmdir.c
src/libpmemfile-posix/truncate.c
src/libpmemfile-posix/unlink.c
src/libpmemfile-posix/utils.c
src/libpmemfile-posix/utils.h
src/libpmemfile-posix/write.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/209)

posix: update ctime when needed

---

src/libpmemfile-posix/fallocate.c
src/libpmemfile-posix/stat.c
tests/posix/rw/rw.cpp
tests/posix/stat/stat.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/211)

Changed errno in libpmemfile-posix and tests to reflect actual POSIX errno codes

---

src/libpmemfile-posix/fallocate.c
src/libpmemfile-posix/fcntl.c
src/libpmemfile-posix/file.c
src/libpmemfile-posix/inode.c
src/libpmemfile-posix/out.c
src/libpmemfile-posix/out.h
src/libpmemfile-posix/rename.c
tests/posix/posix-helpers.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/202)

posix: logging improvements

---

utils/docker/images/install-syscall_intercept.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/213)

common: update syscall_intercept in docker image to the latest version

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/214)

doc: update syscall_intercept variable name

---

utils/docker/images/Dockerfile.fedora-23
utils/docker/images/Dockerfile.fedora-24
utils/docker/images/Dockerfile.ubuntu-15.10
utils/docker/images/Dockerfile.ubuntu-16.10
utils/docker/images/Dockerfile.ubuntu-17.04

Add new docker images to pmemfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/215)

common: add new Dockefiles

---

include/libpmemfile-posix-stubs.h
include/libpmemfile-posix.h

... and remove futimesat from stubs.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/219)

posix: move pmemfile_umask to libpmemfile-posix.h

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/223)

travis: update Travis to Ubuntu 14.04.5 LTS Trusty

---

.travis.yml
utils/docker/build.sh
utils/docker/run-build.sh

#224
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/225)

utils: add support for CXX to docker scripts

---

src/libpmemfile/preload.c
src/libpmemfile/syscall_early_filter.c
src/libpmemfile/syscall_early_filter.h
tests/preload/CMakeLists.txt
tests/preload/pool_locking/pool_locking.c
tests/preload/pool_locking/pool_locking.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/226)

preload: pool locking optimization

---

doc/generated/libpmemfile-posix.3
doc/generated/libpmemfile.1
doc/libpmemfile-posix.3.md
doc/libpmemfile.1.md
include/libpmemfile-posix-stubs.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/227)

doc: man page improvements

---

CMakeLists.txt
tests/posix/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/230)

cmake: move FindThreads to top level cmake file

---

src/libpmemfile-posix/timestamps.c
tests/posix/timestamps/timestamps.cpp

Ref: pmem/pmemfile#231
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/232)

posix: drop permission check for timestamp functions

---

src/libpmemfile/path_resolve.c
src/libpmemfile/preload.c
src/libpmemfile/syscall_early_filter.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/234)

preload: fix typos in comments

---

src/libpmemfile/preload.c

Some refactoring, to make the implementation of dup* syscalls a bit easier.
No functional change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/241)

Minor refactor before dup

---

src/libpmemfile/path_resolve.c
tests/preload/basic_commands/basic_commands.cmake

... when starting from mount point
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/244)

preload: fix path resolution for files outside of pmemfile pool

---

src/libpmemfile/preload.c

The fields `returns_zero` and `returns_ENOTSUP` must
be taken into account only with pmemfile handled files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/247)

preload: fix syscall_early_filter usage

---

src/libpmemfile-posix/dir.c
src/libpmemfile-posix/rename.c
src/libpmemfile-posix/rmdir.c
src/libpmemfile-posix/rmdir.h
src/libpmemfile-posix/symlink.c
src/libpmemfile-posix/truncate.c
src/libpmemfile-posix/unlink.c
src/libpmemfile-posix/unlink.h
tests/posix/symlinks/symlinks.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/239)

Second batch of fixes for issues found by pjdfstest.

---

tests/preload/pool_locking/pool_locking.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/251)

Test pool lock - minor changes

---

tests/preload/CMakeLists.txt
tests/preload/xattr/xattr.c

Closes #254
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/257)

Xattr test fixes

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/260)

doc: extend "limitations" section

---

README.md
src/libpmemfile-posix/CMakeLists.txt
tests/posix/pmemfile_test.hpp
tests/posix/rw/rw.cpp
utils/docker/images/install-nvml.sh

Unfortunately we are still depending on pmemobj's allocator
implementation details because allocation classes API was not merged
to pmemobj yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/266)

Require NVML 1.3

---

CMakeLists.txt
README.md
debian/rules
pmemfile.spec
utils/docker/run-build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/265)

Use RelWithDebInfo build type instead of Release.

---

tests/posix/mt/mt.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/267)

tests: limit multi-threaded tests to 16 threads

---

src/libpmemfile/preload.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/249)

preload: quiet down Coverity's use after free issue

---

tests/preload/pool_locking/pool_locking.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/250)

tests: fixed pool_locking.c fd leak

---

src/tools/antool/antool.py
src/tools/antool/listsyscalls.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/269)

antool: reformat 'for' loops

---

src/libpmemfile-posix/inode.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/268)

[RFC] posix: add work around for out of space issue at inode destruction time

---

tests/antool/CMakeLists.txt
tests/antool/test-antool.sh
tests/antool/test-parser.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/270)

antool: fix running antool tests with vltrace installed

---

.travis.yml
utils/docker/images/Dockerfile.ubuntu-15.10
utils/docker/images/Dockerfile.ubuntu-16.10
utils/docker/images/Dockerfile.ubuntu-17.04

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/280)

Docker images tweaking

---

src/libpmemfile/preload.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/281)

preload: comment update

---

.travis.yml
utils/docker/images/install-syscall_intercept.sh
utils/docker/pull-or-rebuild-image.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/282)

utils: introduce PUSH_IMAGE option

---

utils/docker/images/Dockerfile.fedora-23
utils/docker/images/Dockerfile.fedora-24
utils/docker/images/Dockerfile.fedora-25
utils/docker/images/Dockerfile.ubuntu-15.10
utils/docker/images/Dockerfile.ubuntu-16.04
utils/docker/images/Dockerfile.ubuntu-16.10
utils/docker/images/Dockerfile.ubuntu-17.04

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/284)

antool: add codecov for python to docker images

---

.travis.yml
CMakeLists.txt
src/libpmemfile/CMakeLists.txt
src/libpmemfile/libpmemfile-posix-fd_first.h
src/libpmemfile/libpmemfile-posix-wrappers.h
src/libpmemfile/preload.c
src/libpmemfile/preload.h
utils/docker/build.sh
utils/docker/images/Dockerfile.ubuntu-15.10
utils/docker/images/Dockerfile.ubuntu-16.04
utils/docker/images/Dockerfile.ubuntu-16.10
utils/docker/images/Dockerfile.ubuntu-17.04
utils/docker/run-build.sh
utils/docker/run-coverage.sh
utils/transform/CMakeLists.txt
utils/transform/function_decl_finder.c
utils/transform/function_decl_finder.h
utils/transform/generator.c
utils/transform/generator.h
utils/transform/transform_pmemfile_posix.c
utils/transform/transform_pmemfile_posix_fd_first.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/283)

Use libclang to generate some wrapper functions

---

src/libpmemfile/preload.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/287)

preload: fix call to hook_readlinkat

---

tests/posix/basic/basic.cpp
tests/posix/dirs/dirs.cpp
tests/posix/openp/openp.cpp
tests/posix/permissions/permissions.cpp
tests/posix/rw/rw.cpp
tests/posix/stat/stat.cpp
tests/posix/symlinks/symlinks.cpp
tests/posix/timestamps/timestamps.cpp

Extension for fault injections tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/255)

posix: fault injection extension

---

src/libpmemfile-posix/lseek.c

Fixes after review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/288)

posix: fix lseek to end on directory after review

---

utils/docker/build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/294)

utils: mention OS is build.sh working dir

---

.travis.yml
utils/docker/build.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/295)

utils: make -t docker argument optional in build.sh

---

src/libpmemfile-posix/write.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/298)

posix: simplify write and pwrite functions

---

src/libpmemfile-posix/inode.c
src/libpmemfile-posix/inode.h
src/libpmemfile-posix/lseek.c
src/libpmemfile-posix/read.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/300)

Use readlock in lseek, instead of writelock

---

utils/cstyle

Copy from NVML.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/302)

common: update cstyle script

---

src/tools/antool/antool.py
src/tools/antool/exceptions.py
src/tools/antool/listsyscalls.py
src/tools/antool/syscall.py
src/tools/antool/syscallinfo.py
src/tools/antool/syscalltable.py
src/tools/antool/utils.py
src/valgrind/pmemcheck.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/304)

common: fix license in some files

---

src/libpmemfile/preload.c

Regression from 46e9ebf88e937be60805206790f95a433b6da6a0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/309)

preload: unbreak writev

---

src/libpmemfile-posix/lseek.c
tests/posix/rw/rw.cpp

Implemented lseek to DATA or HOLE on directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/305)

posix: fix lseek to DATA or HOLE on directory

---

tests/antool/.coveragerc
tests/antool/test-antool.sh
tests/antool/test-parser.sh
utils/docker/images/Dockerfile.fedora-23
utils/docker/images/Dockerfile.fedora-24
utils/docker/images/Dockerfile.fedora-25
utils/docker/images/Dockerfile.ubuntu-16.04
utils/docker/images/Dockerfile.ubuntu-16.10
utils/docker/images/Dockerfile.ubuntu-17.04

Ref: #273
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/308)

antool: add code coverage to CodeCov.io reports

---

src/libpmemfile-posix/data.c
src/libpmemfile-posix/fallocate.c
src/libpmemfile-posix/file.h
src/libpmemfile-posix/inode.h
src/libpmemfile-posix/read.c
src/libpmemfile-posix/write.c
tests/posix/CMakeLists.txt
tests/posix/pointer_caching/pointer_caching.cmake
tests/posix/pointer_caching/pointer_caching.cpp

Fixes #79
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/301)

Introduce block_pointer_cache invalidation counter

---

tests/antool/test-antool.sh
tests/antool/test-parser.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/312)

antool: silence "argument expected" warning

---

src/tools/pmemfile-mount.c

Noticed by Coverity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/314)

tools: fix possible buffer overflow

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/316)

doc: improve environment variables documentation

---

.travis.yml
utils/docker/build.sh
utils/docker/sqlite/run-build-sqlite.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/318)

Use SQLite tests to improve code coverage.

---

src/libpmemfile-posix/lseek.c

Fixes issue reported by ASAN:
src/libpmemfile-posix/lseek.c:283:39: runtime error: signed integer overflow: 3 + 9223372036854775807 cannot be represented in type 'long'
SUMMARY: AddressSanitizer: undefined-behavior /src/libpmemfile-posix/lseek.c:283:39 in
src/libpmemfile-posix/lseek.c:294:39: runtime error: signed integer overflow: 9 + 9223372036854775806 cannot be represented in type 'long'
SUMMARY: AddressSanitizer: undefined-behavior src/libpmemfile-posix/lseek.c:294:39 in
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/321)

posix: don't rely on undefined behavior of signed integer overflow

---

src/tools/antool/antool.py
src/tools/antool/exceptions.py
src/tools/antool/listsyscalls.py
src/tools/antool/syscall.py
src/tools/antool/syscallinfo.py
src/tools/antool/syscalltable.py
src/tools/antool/utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/323)

antool: remove (c) from license headers

---

tests/posix/basic/basic.cpp
tests/posix/dirs/dirs.cpp
tests/posix/mt/mt.cpp

Should help with code coverage fluctuations with each build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/329)

Small code coverage improvements.

---

debian/control
debian/pmemfile-tools.install
pmemfile.spec
src/tools/antool/CMakeLists.txt
tests/antool/CMakeLists.txt
utils/build-rpm.sh
utils/docker/images/Dockerfile.fedora-23
utils/docker/images/Dockerfile.fedora-24
utils/docker/images/Dockerfile.fedora-25
utils/docker/images/Dockerfile.ubuntu-16.04
utils/docker/images/Dockerfile.ubuntu-16.10
utils/docker/images/Dockerfile.ubuntu-17.04

Ref: #274
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/315)

antool: package antool

---

src/tools/antool/antool.py
src/tools/antool/listsyscalls.py
src/tools/antool/syscall.py

Replace:
- ```syscall.unsupported``` with ```syscall.unsupported_type```
and:
- ```RESULT_UNSUPPORTED``` with ```RESULT_UNSUPPORTED_AT_ALL```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/328)

antool: change name of a variable

---

src/libpmemfile/preload.c

Ref: #333
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/334)

preload: fix crash when application doesn't flush its streams

---

STATUS.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/338)

Update syscall support status.

---

src/libpmemfile/path_resolve.c
src/libpmemfile/preload.c
utils/docker/build.sh
utils/docker/images/0001-disable-special-files-tests.patch
utils/docker/images/Dockerfile.fedora-23
utils/docker/images/Dockerfile.fedora-24
utils/docker/images/Dockerfile.fedora-25
utils/docker/images/Dockerfile.ubuntu-16.04
utils/docker/images/Dockerfile.ubuntu-16.10
utils/docker/images/Dockerfile.ubuntu-17.04
utils/docker/images/install-pjdfstest.sh
utils/docker/pjdfstest/build-and-test.sh
utils/docker/pjdfstest/pmemfile-summary.log.match
utils/docker/pjdfstest/test.sh

Unfortunately we can't enable it on Travis - process switching is too slow :(.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/335)

pjdfstest integration

---

src/tools/antool/listsyscalls.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/343)

antool: dup* is supported

---

src/libpmemfile/preload.c
tests/preload/basic/basic.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/345)

Fix hook_faccessat

---

utils/docker/prepare-environment.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/348)

docker: Fix a typo in prepare-environment.sh

---

.travis.yml

Not needed probably since #303.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/349)

travis: don't use deprecated image

---

src/libpmemfile/preload.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/354)

preload: fix access mode argument

---

src/libpmemfile/preload.c

Found by Coverity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/350)

preload: fix possible resource leak

---

src/tools/antool/listsyscalls.py
src/tools/antool/syscall.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/353)

antool: more minor fixes

---

utils/docker/external_tests/ltp/failing_short_tests

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/363)

Update the list of LTP failures.

---

CMakeLists.txt
debian/pmemfile-tools.install
pmemfile.spec
src/pmemfile-fuse/CMakeLists.txt
src/pmemfile-fuse/main.c
utils/docker/images/Dockerfile.fedora-23
utils/docker/images/Dockerfile.fedora-24
utils/docker/images/Dockerfile.fedora-25
utils/docker/images/Dockerfile.ubuntu-16.04
utils/docker/images/Dockerfile.ubuntu-16.10
utils/docker/images/Dockerfile.ubuntu-17.04

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/358)

Add FUSE driver using libpmemfile-posix.

---

src/libpmemfile-posix/block_array.c
tests/posix/getdents/none.err.match
utils/docker/external_tests/ltp/failing_short_tests
utils/docker/external_tests/ltp/short_tests
utils/docker/images/install-nvml.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/364)

Downgrade NVML to 1.3

---

tests/posix/rw/rw.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/365)

tests: fix indent in rw.cpp

---

src/tools/antool/listsyscalls.py

... and not the resolved OS-dependent one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/367)

antool: log original path

---

src/libpmemfile-posix/getdents.c
tests/posix/getdents/getdents.cpp
utils/docker/external_tests/ltp/failing_short_tests

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/366)

posix: add getdents einval and enoent handling

---

src/tools/antool/listsyscalls.py
tests/antool/test-fi.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/368)

antool: do not add empty paths to pmem paths

---

src/libpmemfile/preload.c
src/libpmemfile/syscall_early_filter.c
utils/docker/external_tests/ltp/failing_short_tests

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/372)

preload: restore errno before returning to syscall_intercept

---

src/tools/antool/antool.py
src/tools/antool/listsyscalls.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/373)

antool: init pmem_paths only when necessary

---

utils/check_license/check-license.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/381)

utils: merge broken messages in check_license

---

utils/fio/append512.fio
utils/fio/append64.fio
utils/fio/append64k.fio
utils/fio/randread512.fio
utils/fio/randread64.fio
utils/fio/randread64k.fio
utils/fio/randrw512.fio
utils/fio/randrw64.fio
utils/fio/randrw64k.fio
utils/fio/randwrite512.fio
utils/fio/randwrite64.fio
utils/fio/randwrite64k.fio
utils/fio/read512.fio
utils/fio/read64.fio
utils/fio/read64k.fio
utils/fio/rw512.fio
utils/fio/rw64.fio
utils/fio/rw64k.fio
utils/fio/write512.fio
utils/fio/write64.fio
utils/fio/write64k.fio

Add fio benchmarks for pmemfile performance tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/378)

utils: add fio benchmarks

---

src/libpmemfile-posix/stats.c

... and fix indentation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/382)

posix: detect unknown metadata blocks

---

src/libpmemfile-posix/lseek.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/384)

posix: lseek fixes

---

src/libpmemfile-posix/block_array.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/385)

posix: remove performance hack for pre-1.3 pmemobj

---

src/libpmemfile-posix/out.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/387)

posix: fix ASSERTeq/ASSERTne definition

---

src/tools/antool/antool.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/390)

antool: replace "--max_packets" with "--max-packets"

---

utils/docker/external_tests/config.py
utils/docker/external_tests/ltp/ltp.py
utils/docker/external_tests/run-build-suite.sh
utils/docker/external_tests/run-suite.py
utils/docker/external_tests/suite.py
utils/docker/external_tests/tester.py

Option to run single test.
Equivalent test command printed in verbose mode.
Inline hash comment in tests and fails list files omitted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/389)

docker: add various test scripts features

---

src/libpmemfile-posix/mkdir.c
tests/posix/dirs/dirs.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/394)

posix: mkdirat errno fix

---

tests/posix/dirs/dirs.cpp
tests/posix/permissions/permissions.cpp
tests/posix/pmemfile_test.hpp
tests/posix/stat/stat.cpp
tests/posix/symlinks/symlinks.cpp
tests/posix/timestamps/timestamps.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/395)

tests: test *at interfaces with absolute paths

---

src/libpmemfile-posix/data.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/396)

posix: Fix a typo in a comment

---

utils/docker/external_tests/sqlite/failing_short_tests

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/403)

Document why certain Sqlite tests fail.

---

utils/docker/external_tests/ltp/failing_short_tests
utils/docker/external_tests/ltp/short_tests

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/404)

Document why certain LTP tests fail.

---

src/libpmemfile-posix/fcntl.c
utils/docker/external_tests/ltp/failing_short_tests
utils/docker/external_tests/sqlite/failing_short_tests

... and add required locking in F_GETFL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/406)

posix: implement fcntl(..., F_SETFL, ...)

---

src/libpmemfile-posix/inode.c
src/libpmemfile-posix/inode.h
src/libpmemfile-posix/read.c
src/libpmemfile-posix/stat.c
src/libpmemfile-posix/timestamps.c
src/libpmemfile-posix/write.c

Builds on top of #393
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/402)

posix: atime update improvements

---

src/libpmemfile/preload.c
utils/docker/external_tests/ltp/failing_short_tests
utils/docker/external_tests/sqlite/failing_short_tests

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/405)

preload: fix utime and utimes for NULL time

---

src/libpmemfile-posix/dir.c
tests/posix/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/407)

Fix pmemcheck integration!

---

tests/posix/CMakeLists.txt
tests/posix/rw/rw.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/408)

Speedup tests

---

tests/posix/pmemfile_test.cpp
tests/posix/pmemfile_test.hpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/413)

tests: Move some implemenations .hpp -> .cpp

---

src/libpmemfile-posix/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/414)

cmake: remove unused variable

---

tests/antool/output-err-fi-39.log.match
tests/antool/test-fi.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/417)

antool: two minor fixes

---

src/tools/antool/antool.py
src/tools/antool/syscall.py

Fix two PEP 8 coding style violations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/423)

antool: fix coding style

---

src/libpmemfile-posix/blocks.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/428)

posix: changed ifndef and include order in blocks.h

---

src/tools/antool/analyzer.py
src/tools/antool/antool.py
src/tools/antool/converter.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/426)

antool: move linking lists to read_and_parse_data()

---

src/tools/antool/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/427)

antool: add README.md

---

src/libpmemfile-posix/file.c
tests/posix/basic/basic.cpp
tests/posix/pmemfile_test.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/429)

 posix: fix creation of temporary files in directory other than /

---

src/libpmemfile-posix/CMakeLists.txt
src/libpmemfile-posix/chmod.c
src/libpmemfile-posix/chown.c
src/libpmemfile-posix/inode.c
src/libpmemfile-posix/link.c
src/libpmemfile-posix/read.c
src/libpmemfile-posix/rename.c
src/libpmemfile-posix/rmdir.c
src/libpmemfile-posix/statfs.c
src/libpmemfile-posix/timestamps.c
src/libpmemfile-posix/truncate.c
src/libpmemfile-posix/unlink.c
src/libpmemfile-posix/utils.c
src/libpmemfile-posix/utils.h
src/libpmemfile-posix/write.c
tests/posix/basic/basic.cpp
tests/posix/dirs/dirs.cpp
tests/posix/fcntl/fcntl.cpp
tests/posix/openp/openp.cpp
tests/posix/permissions/permissions.cpp
tests/posix/rw/rw.cpp
tests/posix/symlinks/symlinks.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/431)

posix: more tests & minor fixes

---

src/tools/antool/README

Ref: #317
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/433)

antool: add README with usage and examples

---

tests/antool/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/435)

antool: fix finding python3 package

---

src/libpmemfile-posix/out.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/436)

posix: don't evaluate ASSERT args in release mode

---

src/libpmemfile-posix/creds.c
src/libpmemfile-posix/dir.c
src/libpmemfile-posix/file.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/439)

posix: add some logging for permission checks
