- CMakeLists.txt
This variable was already used as a boolean, but
was not specified as a cmake option.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/8)
> Add LONG_TESTS option

- tests/core/CMakeLists.txt
Without this change, when user sets CC/CXX vars before cmake, they do
not propagate to gtest, which means it's built with default compiler.
This can lead to linking error when the difference between compilers
is big enough.
Ref: marcinslusarz/pmemfile#13
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/15)
> tests: fix build with non-default compiler

- src/libpmemfile-core/callbacks.c
- src/libpmemfile-core/data.c
- src/libpmemfile-core/dir.c
- src/libpmemfile-core/file.c
- src/libpmemfile-core/inode.c
- src/libpmemfile-core/inode_array.c
- src/libpmemfile-core/locks.c
Unused arguments removed in the case of static
functions (unless they are used as callback functions),
marked as known unused arguments otherwise.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/20)
> core: remove or mark unused arguments

- tests/core/pmemfile_test.hpp
ASSERT* macros return internally...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/23)
> tests: fix how errors are handled in setup and teardown

- src/libpmemfile-core/file.c
- src/libpmemfile-core/inode.c
It's not required to be supported and I don't see why anyone
would try to pass AT_CWD to those functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/52)
> posix: remove PMEMFILE_AT_CWD support from fstat and fchmod

- src/libpmemfile/preload.c
It should quiet down clang analyzer warnings:
"Passed-by-value struct argument contains uninitialized data
(e.g., via the field chain: 'pmem_fda.file')"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/54)
> preload: always initialize all fields of fd_desc

- tests/preload/preload-helpers.cmake
Currently LD_PRELOAD is still in effect when removing test
directory and we even unset PMEM_IS_PMEM_FORCE, so it means
that removing it steps into the pool and unlinks everything using
msync. This can't be fast.
Just unset LD_PRELOAD in cleanup().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/58)
> tests: speed up preload tests

- src/libpmemfile-posix/dir.c
- src/libpmemfile-posix/dir.h
- src/libpmemfile-posix/file.c
- src/libpmemfile-posix/inode.c
- src/libpmemfile-posix/inode.h
We can get the creation time on an inode directly from it, instead
of returning it in the output parameter.
This should make the code less confusing both to automatic and human
static analyzers ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/60)
> posix: remove time output argument from inode_alloc

- src/libpmemfile-posix/data.c
Truncating did never remove any blocks with offsets
above file size. This problem can't be reproduced
without pmemfile_fallocate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/74)
> posix: fix vinode_truncate

- src/libpmemfile-posix/block_array.c
The relocation of a block was not represented in
the tree of blocks, leaving the tree in an inconsistent
state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/73)
> posix: fix block_list_remove

- src/libpmemfile/preload.c
Pmemfile-posix doesn't care about usage advices and I can't imagine
ever using them. Just return 0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/77)
> preload: add fake fadvise64 support

- src/libpmemfile-posix/data.c
- src/libpmemfile-posix/file.c
- src/libpmemfile-posix/file.h
- tests/posix/dirs/dirs.cpp
Note: It's important to test all functions that accept PMEMfile* as one of its arguments, because mishandled O_PATH is potential security issue (see the change in "open_file").
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/83)
> posix: implement O_PATH open flag

- src/libpmemfile-posix/inode.c
- src/libpmemfile-posix/pool.c
- tests/posix/basic/basic.cpp
- tests/posix/crash/crash.cpp
- tests/posix/pmemfile_test.cpp
- tests/posix/pmemfile_test.hpp
- tests/posix/rw/rw.cpp
Every unlink operation now goes through orphaned_inodes,
so there's not much sense in postponing its creation.
Now we can also stop passing number of inode_arrays to
test_pmemfile_stats_match.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/marcinslusarz/pmemfile/84)
> posix: initialize orphaned_inodes at pool creation time

- CMakeLists.txt
- doc/libpmemfile-posix.3.md
- include/libpmemfile-posix-stubs.h
- include/libpmemfile-posix.h
- src/libpmemfile-posix/data.c
- src/libpmemfile-posix/dir.c
- src/libpmemfile-posix/dir.h
- src/libpmemfile-posix/file.c
- src/libpmemfile-posix/inode.c
- src/libpmemfile-posix/libpmemfile-posix.map
- src/libpmemfile-posix/pool.c
- src/libpmemfile-posix/pool.h
- src/libpmemfile-posix/stubs.c
- src/libpmemfile/path_resolve.c
- src/libpmemfile/preload.c
- src/tools/pmemfile-cat.c
- tests/posix/basic/basic.cpp
- tests/posix/dirs/dirs.cpp
- tests/posix/getdents/getdents.cpp
- tests/posix/permissions/permissions.cpp
- tests/posix/pmemfile_test.cpp
- tests/posix/pmemfile_test.hpp
- tests/posix/rw/rw.cpp
- tests/posix/stat/stat.cpp
- tests/posix/symlinks/symlinks.cpp
On Windows there are problems with types.
Some typedefs don't exist (like ssize_t) and some are wrong (like off_t being always 32-bit and off64_t not existing). The only portable way seems to be to define our own typedefs, use them everywhere and on Linux validate that they have the same size as their native counterparts.
Another problem is with "struct stat". It's defined on Windows, but it has less fields (no st_blksize and st_blocks) and fields that exist have shorter types (eg st_size is 32-bit). There's "struct \_stat64" with some of the fields bigger (st_size is 64-bit), but still some of them are too small (st_uid, st_gid, st_*time, nlink_t, st_ino). The solution presented in this PR is to define "struct pmemfile_stat" exactly like on Linux, use it and validate its size and layout …
> [RFC] posix: port to Windows, part 4

- src/libpmemfile-posix/data.c
- src/libpmemfile-posix/dir.c
- src/libpmemfile-posix/file.c
- src/libpmemfile-posix/inode.c
- src/libpmemfile-posix/pool.c
- tests/posix/mt/mt.cpp
- tests/posix/rw/rw.cpp
One of the goals of this patchset is decoupling of file handle updates from actual read & write.
Thanks to that it's now possible to pread from one file handle from multiple threads.
Builds on top of PR #101.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/102)
> posix: pread & pwrite

- tests/posix/CMakeLists.txt
The CMAKE_THREAD_LIBS_INIT cmake variable is set by the FindThreads
cmake module.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/107)
> Include the FindThreads cmake module

- src/libpmemfile/preload.c
1) Use the actual pmemfile_faccessat function.
2) Remove "flags" argument - it's not implemented by Linux, so
glibc does not use it.
Ref: pmem/pmemfile#105
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/109)
> preload: wire up faccessat properly

- src/libpmemfile/preload.c
- tests/preload/basic_commands/basic_commands.cmake
It allows user change working directory for child process,
without changing it in the parent (which is not possible because
of missing multi-process support).
So instead of:
cd /mnt/pmemfile-mountpoint
ls -l $PATH_RELATIVE_TO_MOUNTPOINT
PMEMFILE_CD=/mnt/pmemfile-mountpoint ls -l $PATH_RELATIVE_TO_MOUNTPOINT
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/113)
> preload: add PMEMFILE_CD env var

- tests/posix/rw/rw.cmake
In commit 6af84afbedafd934dc1a4e1e1bcb7ba76885f4de I renamed two of
the tests, but forgot to change the execution script which excludes
one of them in non-long configurations...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/117)
> tests: speedup rw test

- tests/preload/basic_commands/basic_commands.cmake
Fixes an issue when TEST_DIR/.. is not readable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/122)
> tests: don't look outside of test directory

- CMakeLists.txt
Different versions seem to format code in a bit different way.
This can easily break builds when DEVELOPER_MODE is set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/125)
#124
> cmake: use only clang-format 3.8 or 3.9

- tests/posix/posix-helpers.cmake
- tests/preload/preload-helpers.cmake
"if (${VAR})" evaluates to "if (ON)" when VAR=ON. So now cmake evaluates
"if (ON)" which is not true, because it tries to evaluate variable
"ON" which is not set.
"if (VAR)" works both when VAR=1 or VAR=ON.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/141)
> tests: fix TESTS_USE_FORCED_PMEM=ON

- src/libpmemfile-posix/inode.c
- src/libpmemfile-posix/inode.h
- src/libpmemfile-posix/pool.c
I also refactored unref to open a transaction only when ref count
and nlink count drop to 0. It speeds up tests under pmemcheck.
Ref: pmem/issues#553
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/165)
> posix: make it possible to unlink file when fs is full

- src/libpmemfile-posix/pool.c
We were calling inode_ref even if previous transaction failed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/168)
> posix: fix error handling in pool open/create

- src/libpmemfile/path_resolve.c
I started refactoring path resolution code, (https://github.com/GBuella/pmemfile/commits/path_resolve_refactor), to make it more readable/maintainable, but I'm afraid it will take some more days. So for now, I just removed the related confusing comment in `path_resolve.c`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/169)
> preload: improve one confusing comment

- src/libpmemfile-posix/data.c
- src/libpmemfile-posix/data.h
- src/libpmemfile-posix/file.c
- src/libpmemfile-posix/inode.c
- src/libpmemfile-posix/truncate.c
- src/libpmemfile-posix/truncate.h
- src/libpmemfile-posix/write.c
vinode_rebuild_block_tree when called from [f]truncate could allocate
a ctree, but fail at inserting time, which means ctree would leak.
Do all rebuilds outside of transaction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/193)
> posix: fix possible memory leak in [f]truncate + some cleanups

- tests/posix/CMakeLists.txt
GCC7 introduces new warning called 'Dangling else", due to probable bug in GTest using its functions causes  "dangling else" warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/196)
> Disabled dangling else warning for tests on GCC7

- src/libpmemfile/syscall_early_filter.c
Apparently none of the applications we tested so far used this syscall.
Some versions of "vi" do.
Reported-by: Mateusz Szychowski
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/201)
> preload: finish wiring up creat syscall

- tests/preload/CMakeLists.txt
- tests/preload/setumask.c
Right now we depend on umask being set to 022 in the environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/217)
> tests: set umask for libpmemfile tests

- utils/cstyle
as Perl 5.26 changelog states: "Unescaped literal "{" characters in regular expression paterns are no longer permissible".
This will become "fatal" in Perl 5.30
Message generated by Perl 5.26:
`Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/(?:(?:\b(?:enum|struct|union)\s*[^\{]*)|(?:\s+=\s*)){ <-- HERE / at pmemfile/utils/cstyle line 843.`
Link to changelog:
https://metacpan.org/pod/distribution/perl/pod/perldelta.pod#Unescaped-literal-%22%7B%22-characters-in-regular-expression-patterns-are-no-longer-permissible
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/218)
> cstyle: escape left brace in regular expression

- src/libpmemfile-posix/timestamps.c
Found by clang analyzer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/220)
> posix: remove dead store

- CMakeLists.txt
The CMAKE_LD_FLAGS variable is not used by cmake, therefore some
flags (e.g. -Wl,-z,relro) were never actually used during linking.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/229)
> cmake: Use CMAKE_(EXE|SHARED)_LINKER_FLAGS

- src/libpmemfile-posix/timestamps.c
- tests/posix/timestamps/timestamps.cpp
in POSIX it is valid to have negative value in tm->sec
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/228)
> posix: disable verifying timestamps - tm->sec can be negative

- CMakeLists.txt
- tests/preload/CMakeLists.txt
Still experimental, and the results are usually just segfaults.
Usage:
```
mkdir build
CC=gcc CXX=g++ cmake -DSANITIZERS=ON -DSANITIZERS_PRELOAD=/usr/lib/gcc/x86_64-linux-gnu/6/libasan.so -DBUILD_LIBPMEMFILE=ON ..
make
INTERCEPT_ALL_OBJS=1 ctest -R preload
```
The INTERCEPT_ALL_OBJS is likely required for such tests, so if it turns out that
it cannot work without it, it will be added to preload/CMakeLists.txt in another commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/233)
> cmake: allow sanitizers with libpmemfile

- CMakeLists.txt
- README.md
- tests/posix/CMakeLists.txt
- tests/preload/CMakeLists.txt
Replacing the SANITIZERS option.
This helped me run sanitizers with gcc builds on my desktop. Using the original sanitizers flag resulted in a "stack-buffer-underflow" error being detected by ASAN -- about which (after looking at the instructions around the code being reported) I suspected might be the result of a conflict between ASAN and UBSAN instrumentation. I don't know if it really was or not, but it does disappear when using ASAN only, so I think this patch can be useful.
BTW the error reported by ASAN:
```
=================================================================
==20913==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x7fff6dea785c at pc 0x7f6d78037d1d bp 0x7fff6dea7830 sp 0x7fff6dea7820
READ of size 4 at 0x7fff6dea785c thread T0
#0 0x7f6d78037d1c in …
```
> cmake: Introduce USE_ASAN and USE_UBSAN options

- src/libpmemfile-posix/file.c
- src/libpmemfile-posix/truncate.c
- tests/posix/basic/basic.cpp
- tests/posix/dirs/dirs.cpp
- tests/posix/rw/rw.cpp
1. opening directory with O_RDWR flag should return -1 with EINVAL errno.
2. ftruncate needs to check if a directory was passed to it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/236)
> posix: O_RDWR is not a valid flag to open directories

- src/libpmemfile-posix/write.c
- tests/posix/rw/rw.cpp
When pmemfile_write fails, with no space left, it sets errno to ENOMEM. This is errno returned from libpmemobj.
However when POSIX write fails it will set errno to ENOSPC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/240)
> posix: add ENOSPC errno for pmemfile_write

- src/libpmemfile/path_resolve.c
- src/libpmemfile/preload.c
- src/libpmemfile/preload.h
- src/libpmemfile/syscall_early_filter.c
- tests/preload/CMakeLists.txt
- tests/preload/unix/unix.c
- tests/preload/unix/unix.cmake
- tests/preload/xattr/xattr.c
- tests/preload/xattr/xattr.cmake
- utils/docker/images/Dockerfile.fedora-23
- utils/docker/images/Dockerfile.fedora-24
- utils/docker/images/Dockerfile.fedora-25
- utils/docker/images/Dockerfile.ubuntu-15.10
- utils/docker/images/Dockerfile.ubuntu-16.04
- utils/docker/images/Dockerfile.ubuntu-16.10
- utils/docker/images/Dockerfile.ubuntu-17.04
Bind (for unix sockets) was not handled at all. For getxattr, setxattr, listxattr, llistxattr, removexattr, lremovexattr and chroot paths that pointed outside of pmemfile pool but crossed pmemfile mount point (/mnt/pmemfile/../../tmp/file) were handled incorrectly.
Fixes #181.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/238)
> preload: fix how paths crossing pmemfile mount point are handled

- tests/preload/xattr/xattr.c
- utils/docker/images/Dockerfile.fedora-23
- utils/docker/images/Dockerfile.fedora-24
- utils/docker/images/Dockerfile.fedora-25
- utils/docker/images/Dockerfile.ubuntu-15.10
- utils/docker/images/Dockerfile.ubuntu-16.04
- utils/docker/images/Dockerfile.ubuntu-16.10
- utils/docker/images/Dockerfile.ubuntu-17.04
Ref: #252
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/253)
> tests: fix xattr.h include directive

- src/libpmemfile-posix/lseek.c
- tests/posix/rw/rw.cpp
Calling lseek data or hole with negative offset should return -1 with ENXIO errno.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/256)
> posix: negative offset for lseek is an error

- src/libpmemfile/preload.h
The only reason these happened to work before, was that the
libpmemfile-posix.h header was always included before
the preload.h header.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/248)
> preload: fix forward declarations in preload.h

- src/libpmemfile-posix/lseek.c
- tests/posix/rw/rw.cpp
btrfs and xfs return -1 with ENXIO errno when calling lseek to data/hole on directory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/258)
> posix: fix errno for lseek to data/hole on directory

- src/libpmemfile-posix/lseek.c
- tests/posix/rw/rw.cpp
EOVERFLOW errno is only relevant with 32-bit off_t
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/262)
> posix: fix errno for lseek to CUR and END

- src/libpmemfile-posix/lseek.c
- tests/posix/getdents/getdents.cpp
Implemented lseek seek to end on directory.
It works similar to ext4 - returned value if offset which last directory entry points at.
However in ext4 it is always INT64_MAX - last and empty entry always equals INT64_MAX.
In libpmemfile-posix it is more complicated since last entry does not point at INT64_MAX.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/275)
> posix: fix lseek to end on directory

- src/libpmemfile-posix/file.c
- tests/posix/getdents/getdents.cpp
If somebody has a better name for this commit, please write it :)
This PR fixes a bug which occured when calling getdents for first time with offset different than 0.
file->dir_pos.dir was being not assigned by _pmemfile_openat (file.c:177)
Case when this bug occurs:
- open a directory with some files or directories inside
- set offset with lseek to '1'
- call pmemfile_getdents
- getdents will return 0 instead of buffer with entries
Case when this bug will not occur:
- open a directory with some files or directories inside
- call pmemfile_getdents (default offset is 0)
- getdents will return buffer with entries
- set offset with lseek to '1'
- getdents will return buffer with one less entry than first call - works OK
I added a test for this - getdents.cpp:303. 
Also I added some code for …
> posix: set dir_pos.dir pointer in PMEMfile struct

- src/libpmemfile-posix/fallocate.c
- src/libpmemfile-posix/utils.c
- tests/posix/rw/rw.cpp
fallocate's man page states:
Deallocating file space
Specifying the FALLOC_FL_PUNCH_HOLE flag (available since Linux 2.6.38) in mode deallocates space (i.e., creates a hole) in the byte range starting at offset and continuing for len bytes.
Within the specified range, partial filesystem blocks are zeroed, and whole filesystem blocks are removed from the file.
After a successful call, subsequent reads from this range will return zeroes.
Currently pmemfile_fallocate narrows its punch range to fit blocks inside given range.
Let's say we have 4 blocks at offsets: a, b, c, d...
and we want to punch hole from offset a-5 to d+6
pmemfile_fallocate will set offset to 'a' and length to 'd-a'.
Referring to the manpage this is not correct behaviour - 'partial filesystem blocks are zeroed, and whole …
> posix: fix fallocate PUNCH_HOLE byte zeroing

- src/libpmemfile/libpmemfile-posix-wrappers.h
- utils/transform/transform_pmemfile_posix.c
The code generated by transform_pmemfile_posix.c was sometimes
invalid, in the sense that invalid pointers were logged.
Since those functions which invalidate a pointer
(pmemfile_close, pmemfile_pool_close) have no return value
anyways, the log_write call is moved to be in front of the
forwarding call.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/293)
> utils: alter generation of log_write calls

- utils/docker/build.sh
The build runs with uid 1000 inside docker.
The Precise travis image happens to use this uid for checking
out the sources, but the Trusty travis images uses uid 2000.
This patch makes sure the two uids match.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/303)
> docker: chmod repo

- tests/antool/test-antool.sh
- tests/antool/test-parser.sh
The essence of the fix is adding the condition:
if [ ! "$VLTRACE_SKIP" ]; then
to the test scripts, so that the binary log is not copied now,
because it is unnecessary and wrong when the log is not regenerated.
Copying the log when running parallel tests causes test failures.
Ref: #290
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/311)
> antool: fix moving vltrace binary log for regeneration

- pmemfile-debug.spec
- pmemfile.spec
- tests/posix/CMakeLists.txt
- tests/posix/posix-helpers.cmake
Now ctest -V will print stdout and stderr of all tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/320)
> tests: fail tests when ASAN/UBSAN prints non-fatal message

- src/libpmemfile-posix/lseek.c
SUMMARY: AddressSanitizer: undefined-behavior src/libpmemfile-posix/lseek.c:234:40 in
src/libpmemfile-posix/lseek.c:234:40: runtime error: negation of -9223372036854775808 cannot be represented in type 'pmemfile_off_t' (aka 'long'); cast to an unsigned type to negate this value to itself
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/322)
> posix: handle another case when we rely on undefined behavior in lseek

- src/libpmemfile/CMakeLists.txt
- src/libpmemfile/libpmemfile-posix-fd_first.h
- src/libpmemfile/path_resolve.c
- src/libpmemfile/preload.c
- src/libpmemfile/preload.h
- src/libpmemfile/syscall_early_filter.c
- src/libpmemfile/syscall_early_filter.h
- src/libpmemfile/vfd_table.c
- src/libpmemfile/vfd_table.h
- tests/preload/CMakeLists.txt
- tests/preload/dup/dup.c
- tests/preload/dup/dup.cmake
- tests/preload/nested_dirs/nested_dirs.cmake
- utils/transform/transform_pmemfile_posix_fd_first.c
This is just an RFC as of now.
This PR contains the commits from #283 .
Also needs more comments and whatnot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/291)
---
As one of the side effects, this removes the need for a special cwd_lock being used for all syscalls that are affected by the CWD.
Thus, all syscalls such as `open`, `stat`, etc.. using paths were serialized before, but with this patch, they can run in paralell.
---
Update:
Now that #283 was merged, I rebased it on the current master. But there were a lot of conflicts with the process switching related changes, so this is still work in progress.
I'm sure there are many places where pool_acquire/pool_release …
> vfd_table and dup

- src/libpmemfile-posix/CMakeLists.txt
- tests/posix/CMakeLists.txt
The static library had type UTILITY, which was not usable in the link_target_libraries command.
This patch creates a usable STATIC library, i.e. cmake understads it is a static library.
Also, partial linking is done before hiding symbols.
Also, adding a test using the static library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/313)
> Pmemfile posix static library

- src/tools/antool/listsyscalls.py
The message "All syscalls are supported" was not printed out,
when the verbosity level was greater or equal 2.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/326)
> antool: fix printing that all syscalls are supported

- codecov.yml
- utils/docker/run-coverage.sh
- utils/docker/sqlite/run-build-sqlite.sh
- Submit results for each group of tests separately.
Now it's possible to see how each group of tests contributes to overall
and per-file coverage.
- Add projects.
With that it's possible to see how PR affects each library / tool.
- Disable reporting of coverage for tests, utils, valgrind headers and
error handling wrappers (sys_util.h).
Measuring code coverage of tests and utils (which is run only during
build) doesn't make any sense. Disabling that decreases overall code
coverage, but it's the right thing to do.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/331)
> Codecov.io integration improvements.

- debian/debug/rules
- debian/rules
- pmemfile-debug.spec
- pmemfile.spec
- tests/preload/CMakeLists.txt
- utils/docker/run-coverage.sh
Not all of them are used:
- "nested_dirs" is too slow with nvml 1.3
- "pool_locking" is extremely slow, even with nvml master
- "config_*" tests test only the initialization of libpmemfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/336)
> tests: test process switching using preload tests

- src/libpmemfile/preload.c
- tests/preload/basic/basic.c
- tests/preload/basic_commands/basic_commands.cmake
... when path crosses pmemfile mount point
Ref: #306
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/337)
> preload: fix truncate for paths outside of pmemfile pool

- CMakeLists.txt
- tests/CMakeLists.txt
Introduce the BUILD_LIBPMEMFILE_POSIX_TESTS and
BUILD_LIBPMEMFILE_TESTS options.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/339)
> cmake: Make building of tests optional

- include/libpmemfile-posix-stubs.h
- src/libpmemfile-posix/CMakeLists.txt
- src/libpmemfile-posix/file.c
- src/libpmemfile/libpmemfile-posix-wrappers.h
dup/dup2 is implemented on libpmemfile.so side without any help from
libpmemfile-posix.so.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/342)
> posix: remove pmemfile_dup*

- utils/docker/pjdfstest/pmemfile-summary.log.match
It seems pjdfstest doesn't reliably report failed test number when
test stops with non-zero exit status.
Now that we fixed the underlying issue (I think it was missing support
for dup/dup2), we can see which of the sub-tests are failing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/351)
> docker: update pjdfstest results

- codecov.yml
Even if we could fix tests to always hit all code paths, we can't fix
gcov (which sometimes reports impossible coverage changes). The only
sane solution is to allow coverage to drop by some small number.
0.2% seems to be enough to cover most problems.
https://docs.codecov.io/docs/commit-status#section-threshold
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/352)
> Allow code coverage to drop by 0.2%.

- utils/docker/sqlite/failing_short_tests
Fixed by #354.
There is a bug in run-build-sqlite.sh which does not fail the build when
the list of failed tests changes. It's going to be fixed in #324.
For now just update this list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/356)
> Update the list of failing SQLite short tests.

- src/libpmemfile-posix/truncate.c
- tests/posix/rw/rw.cpp
- utils/docker/external_tests/ltp/failing_short_tests
Fixing error occuring in LTP test ftruncate03.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/361)
> posix: change ftruncate errno for readonly file to EINVAL

- src/tools/antool/listsyscalls.py
- tests/antool/dir_pmem.txt
- tests/antool/test-fi.sh
Move testing pmem paths to fault injection tests,
because the 'dir_pmem.txt' file can be regenerated
and modified.
Remove also incorrect check from realpath().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/370)
> antool: correct test for realpath()

- src/pmemfile-fuse/CMakeLists.txt
Because of:
```
src/pmemfile-fuse/main.c: In function ‘pmemfile_fuse_readdir’:
src/pmemfile-fuse/main.c:146:4: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
unsigned long nextoff = *(unsigned long *)&dirp[i];
^
src/pmemfile-fuse/main.c:149:4: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
unsigned short reclen = *(unsigned short *)&dirp[i];
^
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/371)
> fuse: add -fno-strict-aliasing flag

- utils/docker/external_tests/ltp/short_tests
- utils/docker/images/install-nvml.sh
With #372 merged and disabling of clone02 test we can use nvml from master again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/374)
> Update NVML back to master

- src/libpmemfile-posix/fallocate.c
- src/libpmemfile-posix/file.c
- src/libpmemfile-posix/link.c
- src/libpmemfile-posix/mkdir.c
- src/libpmemfile-posix/rename.c
- src/libpmemfile-posix/symlink.c
There are few cases when ENOSPC would make sense, but I don't see it
specified as valid errno in applicable man page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/383)
> posix: translate ENOMEM to ENOSPC when it's allowed

- tests/preload/xattr/xattr.c
... which can lead to buffer overflow and stack corruption.
Found by Coverity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/386)
> tests: detect too long parameter

- tests/antool/test_syscalls.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/400)
> antool: print error when pthread_create/join fails

- src/tools/antool/antool.py
- src/tools/antool/listsyscalls.py
- tests/antool/output-err-fi-5.log.match
- tests/antool/test-fi.sh
Add the "--print-syscalls-without-path-or-fd" option
which makes it possible to print to the analysis log
also syscalls without a path or a file descriptor among arguments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/401)
> antool: add option for printing syscalls to analysis log

- src/libpmemfile-posix/symlink.c
Fixes regression from 4fb52410a9141197f8d5b1530f8ad1a3d9f3104c on
one of tests in pjdfstest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/412)
> posix: limit symlink length to 4k

- utils/docker/external_tests/tester.py
Example:
```
New test failures introduced in this execution:
rename08
rmdir05
Rerunning test rename08:
rename08    1  TBROK  :  /home/user/ltp/lib/tst_sig.c:233: unexpected signal SIGSEGV(11) received (pid = 3135).
rename08    2  TBROK  :  /home/user/ltp/lib/tst_sig.c:233: Remaining cases broken
rename08    0  TWARN  :  /home/user/ltp/lib/tst_tmpdir.c:337: tst_rmdir: rmobj(/home/user/testdir/mountpoint/renzDHAom) failed: unlink(/home/user/testdir/mountpoint/renzDHAom) failed; errno=2: ENOENT
End out output for rename08
Rerunning test rmdir05:
rmdir05     1  TPASS  :  rmdir(".") failed to remove the current working directory. Returned 22 : Invalid argument
rmdir05     2  TCONF  :  /home/user/ltp/testcases/kernel/syscalls/rmdir/rmdir05.c:112: rmdir on "dir/." supported on Linux
rmdir05 …
```
> external_tests: rerun new failing tests with logging enabled

- src/libpmemfile-posix/inode.c
vinode->parent was compared to vinode (as a "is_root" check) without
holding vinode lock. However exchange won't ever set vinode->parent
to parent, so this race is harmless.
Fixing this race actually simplifies vinode_unref code.
Introduced by 3e3782e41f4f13836a033328130ff1a3b3ac8701.
```
==3433== Conflicting store by thread 13 at 0x06a3b3a0 size 8
==3433==    at 0x4E5A17C: vinode_exchange (rename.c:152)
==3433==    by 0x4E5AE1D: _pmemfile_renameat2 (rename.c:449)
==3433==    by 0x4E5B2E9: pmemfile_renameat2 (rename.c:559)
==3433==    by 0x4789FC: test_exchange(char const*, char const*) (mt.cpp:204)
==3433==    by 0x478A5E: test_exchange_loop(char const*, char const*) (mt.cpp:213)
==3433==    by 0x478B00: rename_worker6() (mt.cpp:261)
==3433==    by 0x485F0A: void std::_Bind_simple<void …
```
> posix: fix harmless race between exchange and unref

- src/tools/antool/antool.py
- src/tools/antool/listsyscalls.py
Move two functions:
- print_always()
- look_for_matching_record()
from listsyscalls.py to antool.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/424)
> antool: move two functions

- src/libpmemfile-posix/file.c
Reported by Coverity.
Fallout from f60769a0891a38dd1decdbd28abdd79ec010b9ac.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/430)
> posix: fix possible use after free

- src/pmemfile-fuse/main.c
- tests/match
Part of #437 that passes tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemfile/438)
> fuse: bug fixes
